felt/geo

lib/geo/postgis/extension.ex, test/geo/postgis_test.exs
I see errors when a table contains text columns, it looks like the extension is trying to parse the wrong columns.
This works for me... Not sure if it has other implications though.
=> Fix for tables containing text columns

README.md
It didn't work when I used the existing documentation for the Ecto usage. When changing it to this it worked, as this is the correct name of the Postgrex Extension.
=> Correct Postgrex extension name in Ecto documentation

CHANGELOG.md, README.md, lib/geo.ex, lib/geo/geo_json.ex, mix.exs, test/geo/json_test.exs
See #24. This adds an opts parameter to skip json encoding when needed.
```elixir
iex(3)> Geo.JSON.encode(point, [skip_json: true])
%{ type: "Point", coordinates: [100.0, 0.0] }
```
=> Added an opts parameter to Geo.JSON.encode to allow for skipping json encoding

mix.exs, mix.lock, test/geo/ecto_test.exs
There are warnings running the tests due to Repo.one being deprecated
but replacing the calls with Repo.first would preclude running against
Ecto 1.1.x.
=> Allow running Geo against Ecto 2.0-beta release

lib/geo/wkt.ex, test/geo/wkt_test.exs
Valid WKT strings such as "POLYGON((35 10,45 45,15 40,10 20,35 10), (20 30,35 35,30 20,20 30))" where a space is added between the comma and the open-parens of the hole are being decoded to a single list of points.
```
iex(1)> Geo.WKT.decode("POLYGON((35 10,45 45,15 40,10 20,35 10),(20 30,35 35,30 20,20 30))")
%Geo.Polygon{coordinates: [[{35, 10}, {45, 45}, {15, 40}, {10, 20}, {35, 10}],
[{20, 30}, {35, 35}, {30, 20}, {20, 30}]], srid: nil}
iex(2)> Geo.WKT.decode("POLYGON((35 10,45 45,15 40,10 20,35 10), (20 30,35 35,30 20,20 30))")
%Geo.Polygon{coordinates: [[{35, 10}, {45, 45}, {15, 40}, {10, 20}, {35, 10},
{20, 30}, {35, 35}, {30, 20}, {20, 30}]], srid: nil}
```
This PR addresses this by using a Regex in the split instead of a static `"),("` string.
=> Add handling of spaces between comma and open-parens on WKT.

mix.exs
Thanks for geo I use it in production with an API for a client. 
And since yesterday Ecto 2.0 was released I want to be able to use `geo` and `ecto` with 2.0 that's why I changed the dependency from `2.0-rc` to `2.0`
=> Remove release candidate and allow for 2.0

lib/geo/postgis.ex, test/geo/ecto_test.exs
@bryanjos forgot to send you this PR the other day. Let me know if the test is okay.  It transforms the multipoint to EPSG:3452 http://www.spatialreference.org/ref/epsg/3452/
=> Add st_transform postgis function

lib/geo.ex
while the readme.md was updated to reflect the change from extensions to a type definition, the documentation in geo.ex wasn't. Suggested update.
=> updated ecto related documentation

.travis.yml, lib/geo/postgis.ex, test/geo/ecto_test.exs
Switch to using ST_DistanceSphere instead. This avoids frequent warnings
in the postgresql server log.
=> Avoid call to deprecated ST_Distance_Sphere

README.md
I hit some snags setting this on on a Phoenix project. This is totally my fault, I have no idea what I am doing. But I found the Ecto docs very helpful, so I thought I'd add a reference to them in the readme.
https://hexdocs.pm/ecto/Ecto.Adapters.Postgres.html#module-extensions
Cheers!
=> Reference Ecto extension docs

lib/geo/wkt.ex
Hi, 
I replaced all the strip function calls with trim, since strip was deprecated in Elixir 1.5.
Cheers,
Sebastian A. Espindola
=> fixing String.strip() deprecations in Elixir 1.5

lib/geo/geo_json.ex, test/geo/json_test.exs
PostGIS' `ST_AsGeoJSON()` function (http://www.postgis.net/docs/ST_AsGeoJSON.html) produces a CRS field with a colon between `EPSG` and the SRID integer, eg `EPSG:4326`. Googling around, this appears to be the standard way of doing things. The existing code expects no colon (`EPSG4326`). I've changed it to match what seems to be the standard.
The catch with this change is that anyone who's encoded a geom with the old code will not be able to decode with the new version. If you think that's likely to be an issue, it could be resolved by adding back in the old clause for `get_srid/1` between the new version and the version that takes `nil`. I didn't do that in order to keep the code simple, but I have no problem with doing so.
=> Change handling of EPSG/SRID to match standard

lib/geo/json.ex, lib/geo/json/decoder.ex, lib/geo/json/encoder.ex, test/geo/json_test.exs
- Fix an issue when you pass a random type to the decoding process
- Create Encoder and Decoder modules following Poison code style, I think this improve the readability
`Geo.JSON.encode` becomes `Geo.JSON.encode!`
`Geo.JSON.decode` becomes `Geo.JSON.decode!`
Because normally `!` from code style on Elixir people would expect a error to be rise if something goes wrong.
=> Improve Geo.JSON encoding and decoding

lib/geo/wkb/decoder.ex, test/geo/wkb_test.exs
Currently `Geo.WKB.decode/2` throws an exception when decoding
an empty multipolygon:
```
Geo.WKB.decode!("0106000020E610000000000000")
** (MatchError) no match of right hand side value: ""
(geo) lib/geo/wkb/reader.ex:6: Geo.WKB.Reader.new/1
(geo) lib/geo/wkb/decoder.ex:35: Geo.WKB.Decoder.decode!/2
(geo) lib/geo/wkb/decoder.ex:160: Geo.WKB.Decoder.decode_coordinates/2
(geo) lib/geo/wkb/decoder.ex:50: Geo.WKB.Decoder.decode!/2
```
This PR fixes it.
=> Support WKB empty multipolygons

README.md, lib/geo.ex, lib/geo/json/decoder.ex, lib/geo/json/encoder.ex, test/geo/json_test.exs
Hey! I was missing the JSON parsing of PointZ, I'm super new to Elixir so I just gave it a try. 
Let me know if I missed something.
=> Add PointZ to Geo.Json decoder and encoder, add tests

lib/geo/json/decoder.ex, test/geo/json_test.exs
This adds the support for decoding GeoJSON [Feature](https://tools.ietf.org/html/rfc7946#section-3.2) and [FeatureCollection](https://tools.ietf.org/html/rfc7946#section-3.3).
It should also be compatible with GeoCodeJSON.
Encoding support makes little sense, so I didn't added any.
=> Add JSON decoding support for GeoJSON Feature & FeatureCollection

lib/geo/utils.ex
The `reverse_byte_order/1` function was not especially quick. In an Ecto postgres query with a large number of geo fields, it ended up taking a significant percentage of the total time. I have some `fprof` files if you're interested in details, but the short version is that this change reduced the time to process the geo fields on 2000 objects (running under `fprof`, so the times are larger than they would otherwise be) from 1358ms to 142ms for the same query (the first value represented 42% of the total query time).
=> Optimise reverse_byte_order/1

lib/geo/json/decoder.ex, lib/geo/json/encoder.ex, test/geo/json_test.exs
This will finish the support for decoding all valid geojson files that follow the rfc. If there is data that `Geo` does not support that extra data is simply thrown away.
Also allows us to encode PointZ in accordance with the GeoJSON rfc.
Encoder:
* `%Point{}`  ➡️  `{"type": "Point", "coordinates": [1,2]}`
* `%PointZ{}` ➡️ `{"type": "Point", "coordinates": [1,2, 3]}`
Decoder:
* `{"type": "Point", "coordinates": [1,2]}` ➡️ `%Point{}`
* `{"type": "Point", "coordinates": [1,2,3]}` ➡️  `%PointZ{}`
* `{"type": "OtherGeometriesWith3Elements", "coordinates": [1,2,3]}` ➡️  __discard the 3rd element__
The encoding part still gives error on `%PointM{}` and `%PointZM{}`. If we want to we can simply translate those the the closest thing as such:
* `%PointZM{}` -> `{"type": "Point", "coordinates": …
=> Correctly encode and decode all valid geojson

README.md, lib/geo.ex, lib/geo/json/decoder.ex, lib/geo/json/encoder.ex, lib/geo/line_stringz.ex, lib/geo/multi_line_stringz.ex, lib/geo/multi_pointz.ex, lib/geo/multi_polygonz.ex, lib/geo/polygonz.ex, lib/geo/utils.ex, lib/geo/wkb/decoder.ex, lib/geo/wkb/encoder.ex, lib/geo/wkt/decoder.ex, lib/geo/wkt/encoder.ex
We use types such as MultiPolygonZ, and so need consistent support for the 3D as well as the 2D datasets. These changes add them to this repo. A separate pull request to geo_postgis follows to make it available to ecto...
=> Add 3D versions of the various datatypes

lib/geo/geometry_collection.ex, lib/geo/json.ex, lib/geo/json/decoder.ex, lib/geo/json/encoder.ex, lib/geo/line_string.ex, lib/geo/line_stringz.ex, lib/geo/multi_line_string.ex, lib/geo/multi_line_stringz.ex, lib/geo/multi_point.ex, lib/geo/multi_pointz.ex, lib/geo/multi_polygon.ex, lib/geo/multi_polygonz.ex, lib/geo/point.ex, lib/geo/pointm.ex, lib/geo/pointz.ex, lib/geo/pointzm.ex, lib/geo/polygon.ex, lib/geo/polygonz.ex, lib/geo/wkb.ex, lib/geo/wkb/encoder.ex, lib/geo/wkt.ex, lib/geo/wkt/encoder.ex
I pulled `geo` into a library of mine and had some dialyzer issues. I ran dialyzer against `geo` and uncovered a few incorrect specs. This PR addresses them.
- `Map.t()` isn't a valid type. Changed it to `map()`.
- The `Geo.WKT.encode!/1` spec had a typo (missing the `!`)
- All the structs that make up the `Geo.geometry()` type could return `nil` under the `srid` key. Technically, you'd only need to change one of the struct specs, but it felt like the right thing to change them all.
- A few different `WKT` and `WKB` functions related to encoding were spec'd to accept `binary` as their first argument. Should be `Geo.geometry()` instead.
=> Tweaking type specs

lib/geo/json.ex, lib/geo/json/encoder.ex, test/geo/json_test.exs
* Geo.JSON.encode!/1 behaves exactly the same
* Geo.JSON.encode!/2 accepts `feature: true` to use new behavior
see #119 
agree with @achedeuzot, thanks for the great lib. here is an attempt to address encoding to GeoJSON Feature/FeatureCollection types without breaking existing structure.
=> add GeoJSON Feature and FeatureCollection encoding

lib/geo/point.ex
Hi there! I know this wasn't asked for, so my feelings won't be hurt if it doesn't make it in, but we use this under the hood at Community and it felt like a small way to say thanks.
I watched a coworker make an identical mistake to one I made about a year ago and it seemed like this might help. People who aren't used to post gis, or GIS in general, will typically refer back to when they learned about coordinates and at least in my upbringing, latitude is always mentioned first, the opposite of what is needed here.
When I went through this last year, slightly more detailed type spec would have saved me a few days of cleanup after a botched migration.
If you would like me to do this in more places or if there is anything else you would like to see from this, please just let me know.
Thanks …
=> Update typespec to make Point easier to use.

lib/geo/json.ex
The documents had an extraneous variable in the piped function call.
=> Removing variable in piped geo json decode call

lib/geo/json/decoder.ex, test/geo/json_test.exs
This PR adds support for decoding a `LineStringZ` from a GeoJSON.
=> Add JSON decoding support for LineStringZ

lib/geo.ex, mix.exs
Hi!
As @wojtekmach mentioned, `Jason` support introduced earlier added a hard dependency on Jason, so the geo would fail to compile as a result.
I've made `jason` optional and guarded `Jason.Encoder` protocol implementation with an `if`.
Resolves https://github.com/bryanjos/geo/pull/141#discussion_r518342383_
=> Make Jason optional

lib/geo/wkb/decoder.ex, test/geo/wkb_test.exs
=> Handle MultiLineString with empty coordinates

config/config.exs
I'd assume the logger level was to silence out stuff in tests but that doesn't seem to be the case.
=> Remove config/

lib/geo/json/decoder.ex, test/geo/json_test.exs
According to the GeoJSON spec:
> A position is an array of numbers.  There MUST be two or more
> elements.  The first two elements are longitude and latitude, or
> easting and northing, precisely in that order and using decimal
> numbers.  Altitude or elevation MAY be included as an optional third
> element.
>
> Implementations SHOULD NOT extend positions beyond three elements
> because the semantics of extra elements are unspecified and
> ambiguous.  Historically, some implementations have used a fourth
> element to carry a linear referencing measure (sometimes denoted as
> "M") or a numerical timestamp, but in most situations a parser will
> not be able to properly interpret these values.  **The interpretation
> and meaning of additional elements is beyond the scope of this
> …
=> Ignore extra elements in positions

lib/geo/json/decoder.ex, test/geo/json_test.exs
Hi there! Thanks for putting together such a rock-solid library. We've been using it happily in production for over a year. ☺️
I recently encountered an odd corner of the GeoJSON spec thanks to a user-submitted file, and I'd love to have a way to handle it in Geo. [Per RFC 7946](https://www.rfc-editor.org/rfc/rfc7946#section-3.2), a Feature object's `"geometry"` member can be either a Geometry object or a JSON null value.
Prior to this patch, you would get a `BadMapError` if you attempted to decode GeoJSON that included a feature with null geometry, thereby aborting the processing of _all_ the data—in the case I encountered, one out of ~1000 features in a FeatureCollection was like this. With this patch, that Feature will be filtered out of the FeatureCollection, or in the case of a …
=> Support null feature geometries

.github/actions/elixir-setup/action.yml, .github/dependabot.yml, .github/workflows/elixir-build-and-test.yml, .github/workflows/elixir-quality-checks.yml, .github/workflows/elixir-retired-packages-check.yml, lib/geo/geometry_collection.ex, lib/geo/line_string.ex, lib/geo/line_stringz.ex, lib/geo/multi_point.ex, lib/geo/multi_pointz.ex, lib/geo/pointm.ex, lib/geo/pointz.ex, lib/geo/polygonz.ex, lib/geo/wkb.ex, mix.exs, test/geo/json_test.exs, test/geo/wkt_test.exs
Adds GitHub Actions for:
- build & test for all combinations of Elixir 1.10, 1.11, 1.12, 1.13, 1.14, and 1.15, plus OTP 22, 23, 24, 25, and 26
- basic code quality checks (and a formatting fix and unused dependency removal to match)
- checking for retired Hex dependencies
Also updates the maintainers list and URL to reflect the new Felt org.
=> Add GitHub Actions CI

lib/geo/json/decoder.ex, lib/geo/json/encoder.ex, lib/geo/wkb/decoder.ex, lib/geo/wkb/encoder.ex, test/geo/json_test.exs, test/geo/wkb_test.exs
Adds support for (E)WKB and GeoJSON conversion for Empty Point.
An Empty Point in
- in WKB is represented as `Point(NaN NaN)`.
- in GeoJson is represented as `{"type" => "Point", "coordinates" => []}`
This PR implements an Empty Point in Geo as `%Geo.Point{coordinates: nil}`
=> Support for Empty Point

.github/workflows/elixir-build-and-test.yml, .github/workflows/elixir-quality-checks.yml, .github/workflows/elixir-retired-packages-check.yml
I had copied these templates from a project where the main branch was named `main`. For the time being, I've just updated the name here to match the project's main branch name of `master`. (Longer term, we should look into what might break in people's workflows if we moved to `main`.)
=> Run CI on merge to master

lib/geo/wkb/encoder.ex
This was breaking the build because we were unintentionally duplicating these function clauses (see the `for {endian, endian_atom, modifier} . . .` stuff).
=> Fix compile warnings

CHANGELOG.md, README.md, mix.exs
Bumps the version in both `mix.exs` and the readme, and adds release notes.
=> Prepare to release v3.6.0

test/geo/json_test.exs
I merged a PR where I'd inadvertently [broken the tests](https://github.com/felt/geo/actions/runs/10639829036/job/29498534515) because it failed to run the tests at all, and the retry said there were no tests to run. 🤦‍♂️ 
Open the test of the latest version of Elixir from CI; confirm the tests actually ran, rather than failing and passing the CI step anyway.
=> Fix broken test

CHANGELOG.md, README.md, lib/geo/json.ex, lib/geo/json/decoder.ex, mix.exs, test/geo/json_test.exs
The GeoJSON spec [indicates](https://tools.ietf.org/html/rfc7946#section-4) that all GeoJSON should be assumed to use the WGS 84 datum by default. We should be permissive and allow overriding that datum (as we did previously), but I think the correct behavior here is to make the datum explicit in our decoded `Geo.Geometry.t()` values.
This is a breaking change, but one which I expect to have quite little impact on users. (See the CHANGELOG.md for more.)
Resolves #129
=> Default decoded GeoJSON to SRID 4326 (WGS 84) per the spec

lib/geo/json/decoder.ex, lib/geo/utils.ex, test/geo/json_test.exs, test/geo/utils_test.exs
String.to_float will not handle integer representations, instead Float.parse can be used, I almost wanted to roll something myself until I remembered Float.parse exists.
#220
=> Use a custom string_to_float/1 function instead of plain String.to_float for ensure_numeric

mix.exs
The default branch name for ExDoc links is "main", but this project's primary branch is "master".
This pull request fixes the issue by specifying the correct `:source_ref` option in the ExDoc config.
=> Fix ExDoc source ref links not working due to wrong branch name

lib/geo.ex
This PR aims to add the `Geo.LineStringM` struct to the main `geo.ex` file so that it can be used when Geo is installed from hex. The PR is related to issue #240.
=> Add LineStringM to main geo.ex file
